- 1.1.10
- _NAME: Signature M650 Mouse
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, adc_power_management]
  _battery: 4100
  _modelId: B02A00000000
  _sensitive: {divert-keys: true, dpi: true, lowres-scroll-mode: true, reprogrammable-keys: true}
  _serial: D3A854E7
  _unitId: D3A854E7
  _wpid: B02A
  divert-keys: {82: 0, 83: 1, 86: 1}
  dpi: 1000
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86}
